/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 * Author: Benjamin Chao <benjamin.chao@mediatek.com>
 */

#ifndef _CLK_MT6897_FMETER_H
#define _CLK_MT6897_FMETER_H

/* generate from clock_table.xlsx from TOPCKGEN DE */

/* CKGEN Part */
#define FM_AXI_CK				1
#define FMP_FAXI_CK				2
#define FM_U_FAXI_CK				3
#define FM_BUS_AXIMEM_CK			4
#define FM_DISP0_CK				5
#define FM_DISP1_CK				6
#define FM_OVL0_CK				7
#define FM_OVL1_CK				8
#define FM_MDP0_CK				9
#define FM_MDP1_CK				10
#define FM_MMINFRA_CK				11
#define FM_DSP_CK				12
#define FM_MFG_REF_CK				13
#define FM_MFGSC_REF_CK				14
#define FM_CAMTG2_CK				15
#define FM_CAMTG3_CK				16
#define FM_CAMTG4_CK				17
#define FM_CAMTG5_CK				18
#define FM_CAMTG6_CK				19
#define FM_CAMTG7_CK				20
#define FM_CAMTG8_CK				21
#define FM_UART_CK				22
#define FM_MSDC_MACRO_1P_CK			23
#define FM_MSDC_MACRO_2P_CK			24
#define FM_MSDC30_1_CK				25
#define FM_MSDC30_2_CK				26
#define FM_AUD_INTBUS_CK			27
#define FM_ATB_CK				28
#define FM_DP_CK				29
#define FM_DISP_PWM_CK				30
#define FM_USB_CK				31
#define FM_USB_XHCI_CK				32
#define FM_I2C_CK				33
#define FM_SENINF_CK				34
#define FM_SENINF1_CK				35
#define FM_SENINF2_CK				36
#define FM_SENINF3_CK				37
#define FM_SENINF4_CK				38
#define FM_SENINF5_CK				39
#define FM_DXCC_CK				40
#define FM_AUD_ENGEN1_CK			41
#define FM_AUD_ENGEN2_CK			42
#define FM_AES_UFSFDE_CK			43
#define FM_U_CK					44
#define FM_U_MBIST_CK				45
#define FM_PEXTP_MBIST_CK			46
#define FM_AUD_1_CK				47
#define FM_AUD_2_CK				48
#define FM_ADSP_CK				49
#define FM_AUDIO_LOCAL_B			50
#define FM_DPMAIF_MAIN_CK			51
#define FM_VENC_CK				52
#define FM_VDEC_CK				53
#define FM_PWM_CK				54
#define FM_AUDIO_H_CK				55
#define FM_MCUPM_CK				56
#define FM_MEM_SUB_CK				57
#define FMP_FMEM_SUB_CK				58
#define FM_U_FMEM_SUB_CK			59
#define FM_EMI_N_CK				60
#define FM_EMI_S_CK				61
#define FM_CCU_AHB_CK				62
#define FM_AP2CONN_HOST_CK			63
#define FM_IMG1_CK				64
#define FM_IPE_CK				65
#define FM_MCU_ACP_CK				66
#define FM_MCU_L3GIC_CK				67
#define FM_MCU_INFRA_CK				68
#define FM_IPS_CORE_CK				69
#define FM_TL_CK				70
#define FM_PEXTP_FAXI_CK			71
#define FM_PEXTP_FMEM_SUB_CK			72
#define FM_EMI_IF_546_CK			73
#define FM_SPI0_CK				74
#define FM_SPI1_CK				75
#define FM_SPI2_CK				76
#define FM_SPI3_CK				77
#define FM_SPI4_CK				78
#define FM_SPI5_CK				79
#define FM_SPI6_CK				80
#define FM_SPI7_CK				81
#define FM_MMUP_CK				82
#define FM_DBGAO_26M_CK				83
#define FM_MFG_EB_CK				84
#define FM_CAM_CK				85
#define FM_CAMTM_CK				86
#define FM_DPE_CK				87
#define FM_UARTHUB_BCLK_CK			88
#define FM_CKGEN_NUM				89
/* ABIST Part */
#define FM_LVTS_CKMON_LM			4
#define FM_LVTS_CKMON_L8			5
#define FM_LVTS_CKMON_L7			6
#define FM_LVTS_CKMON_L6			7
#define FM_LVTS_CKMON_L5			8
#define FM_LVTS_CKMON_L4			9
#define FM_LVTS_CKMON_L3			10
#define FM_LVTS_CKMON_L2			11
#define FM_LVTS_CKMON_L1			12
#define FM_ADSPPLL_CK				28
#define FM_APLL1_CK				29
#define FM_APLL2_CK				30
#define FM_DSI1_LNTC_DSICK_FQMTR		32
#define FM_DSI1_MPPLL_TST_CK			33
#define FM_CSI0A_DPHY_DELAYCAL_CK		37
#define FM_CSI0B_DPHY_DELAYCAL_CK		38
#define FM_DSI0_LNTC_DSICK_FQMTR		49
#define FM_DSI0_MPPLL_TST_CK			50
#define FM_MAINPLL_CK				52
#define FM_MDPLL1_FS26M_GUIDE			53
#define FM_MMPLL_CK				55
#define FM_MMPLL_DIV3_CK			56
#define FM_MPLL_CK				57
#define FM_MSDCPLL_CK				58
#define FM_IMGPLL_CK				59
#define FM_EMIPLL_CK				60
#define FM_TVDPLL_CK				61
#define FM_ULPOSC2_MON_V_VCORE_CK		62
#define FM_ULPOSC_MON_V_VCORE_CK		63
#define FM_UNIVPLL_CK				64
#define FM_UNIVPLL_192M_CK			66
#define FM_U_CLK2FREQ				67
#define FM_WBG_DIG_BPLL_CK			68
#define FM_466M_FMEM_INFRASYS			70
#define FM_MCUSYS_ARM_OUT_ALL			71
#define FM_MSDC11_IN_CK				73
#define FM_MSDC12_IN_CK				74
#define FM_MSDC21_IN_CK				75
#define FM_MSDC22_IN_CK				76
#define FM_F32K_VCORE_CK			79
#define FM_UNIVPLL_DIV3_CK			84
#define FM_APLL2_CKDIV_CK			85
#define FM_APLL1_CKDIV_CK			86
#define FM_ADSPPLL_CKDIV_CK			87
#define FM_TVDPLL_CKDIV_CK			88
#define FM_MPLL_CKDIV_CK			89
#define FM_MMPLL_CKDIV_CK			90
#define FM_MAINPLL_CKDIV_CK			91
#define FM_IMGPLL_CKDIV_CK			92
#define FM_EMIPLL_CKDIV_CK			93
#define FM_MSDCPLL_CKDIV_CK			94
#define FM_RO_OUT_FM				95
#define FM_ABIST_NUM				96
/* VLPCK Part */
#define FM_SCP_CK				1
#define FM_SCP_SPI_CK				2
#define FM_SCP_IIC_CK				3
#define FM_SCP_SPI_HSPD_CK			4
#define FM_SCP_IIC_HSPD_CK			5
#define FM_PWRAP_ULPOSC_CK			6
#define FM_SPMI_M_CK				8
#define FM_SPMI_P_CK				9
#define FM_DVFSRC_CK				10
#define FM_PWM_VLP_CK				11
#define FM_AXI_VLP_CK				12
#define FM_SYSTIMER_26M_CK			13
#define FM_SSPM_CK				14
#define FM_SRCK_CK				15
#define FM_SRAMRC_CK				16
#define FM_CAMTG_CK				17
#define FM_IPS_CK				18
#define FM_F26M_SSPM_CK				19
#define FM_ULPOSC_SSPM_CK			20
#define FM_CCUSYS_CK				21
#define FM_CCUTM_CK				22
#define FM_VLPCK_NUM				23

enum fm_sys_id {
	FM_TOPCKGEN = 0,
	FM_APMIXEDSYS = 1,
	FM_VLP_CKSYS = 2,
	FM_MFGPLL = 3,
	FM_MFGSCPLL = 4,
	FM_ARMPLL_LL = 5,
	FM_ARMPLL_BL = 6,
	FM_ARMPLL_B = 7,
	FM_CCIPLL = 8,
	FM_PTPPLL = 9,
	FM_SYS_NUM = 10,
};

#endif /* _CLK_MT6897_FMETER_H */
