


#define CONFIG_SUPPORTED_TOUCHES              (10u)
#define CONFIG_COMMS_SLAVE_INPUT_BUFFER_SIZE  (1024u)
#define CONFIG_COMMS_SLAVE_OUTPUT_BUFFER_SIZE (1024u)
#define CONFIG_ESWIN_TOUCH_PROTOCOL_VERSION_3 (3u)
#define CONFIG_ESWIN_TOUCH_PROTOCOL_VERSION_2 (2u)
#define CONFIG_ESWIN_TOUCH_PROTOCOL_VERSION   (CONFIG_ESWIN_TOUCH_PROTOCOL_VERSION_3)