# SPDX-License-Identifier: GPL-2.0

ifeq ($(CONFIG_DEVICE_MODULES_ALLOW_BUILTIN),y)

LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)

obj-y += ../$(DEVICE_MODULES_REL_DIR)/drivers/tty/serial/8250/
obj-y += ../$(DEVICE_MODULES_REL_DIR)/drivers/dma/mediatek/

endif
