/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 * Author: Chuan-Wen Chen <chuan-wen.chen@mediatek.com>
 */

#ifndef _DT_BINDINGS_CLK_MT6878_H
#define _DT_BINDINGS_CLK_MT6878_H

/* TOPCKGEN */
#define CLK_TOP_AXI_SEL					0
#define CLK_TOP_AXIP_SEL				1
#define CLK_TOP_AXI_UFS_SEL				2
#define CLK_TOP_BUS_AXIMEM_SEL				3
#define CLK_TOP_DISP0_SEL				4
#define CLK_TOP_MMINFRA_SEL				5
#define CLK_TOP_MMUP_SEL				6
#define CLK_TOP_CAMTG_SEL				7
#define CLK_TOP_CAMTG2_SEL				8
#define CLK_TOP_CAMTG3_SEL				9
#define CLK_TOP_CAMTG4_SEL				10
#define CLK_TOP_CAMTG5_SEL				11
#define CLK_TOP_CAMTG6_SEL				12
#define CLK_TOP_UART_SEL				13
#define CLK_TOP_SPI0_SEL				14
#define CLK_TOP_SPI1_SEL				15
#define CLK_TOP_SPI2_SEL				16
#define CLK_TOP_SPI3_SEL				17
#define CLK_TOP_SPI4_SEL				18
#define CLK_TOP_SPI5_SEL				19
#define CLK_TOP_SPI6_SEL				20
#define CLK_TOP_SPI7_SEL				21
#define CLK_TOP_MSDC_0P_SEL				22
#define CLK_TOP_MSDC50_0_HCLK_SEL			23
#define CLK_TOP_MSDC50_0_SEL				24
#define CLK_TOP_AES_MSDCFDE_SEL				25
#define CLK_TOP_MSDC_1P_SEL				26
#define CLK_TOP_MSDC30_1_SEL				27
#define CLK_TOP_MSDC30_1_HCLK_SEL			28
#define CLK_TOP_AUD_INTBUS_SEL				29
#define CLK_TOP_ATB_SEL					30
#define CLK_TOP_USB_TOP_SEL				31
#define CLK_TOP_USB_XHCI_SEL				32
#define CLK_TOP_I2C_SEL					33
#define CLK_TOP_SENINF_SEL				34
#define CLK_TOP_SENINF1_SEL				35
#define CLK_TOP_SENINF2_SEL				36
#define CLK_TOP_SENINF3_SEL				37
#define CLK_TOP_AUD_ENGEN1_SEL				38
#define CLK_TOP_AUD_ENGEN2_SEL				39
#define CLK_TOP_AES_UFSFDE_SEL				40
#define CLK_TOP_UFS_SEL					41
#define CLK_TOP_UFS_MBIST_SEL				42
#define CLK_TOP_AUD_1_SEL				43
#define CLK_TOP_AUD_2_SEL				44
#define CLK_TOP_DPMAIF_MAIN_SEL				45
#define CLK_TOP_VENC_SEL				46
#define CLK_TOP_VDEC_SEL				47
#define CLK_TOP_PWM_SEL					48
#define CLK_TOP_AUDIO_H_SEL				49
#define CLK_TOP_MCUPM_SEL				50
#define CLK_TOP_MEM_SUB_SEL				51
#define CLK_TOP_MEM_SUBP_SEL				52
#define CLK_TOP_MEM_SUB_UFS_SEL				53
#define CLK_TOP_EMI_N_SEL				54
#define CLK_TOP_DSI_OCC_SEL				55
#define CLK_TOP_AP2CONN_HOST_SEL			56
#define CLK_TOP_IMG1_SEL				57
#define CLK_TOP_IPE_SEL					58
#define CLK_TOP_CAM_SEL					59
#define CLK_TOP_CCUSYS_SEL				60
#define CLK_TOP_CAMTM_SEL				61
#define CLK_TOP_CCU_AHB_SEL				62
#define CLK_TOP_CCUTM_SEL				63
#define CLK_TOP_MSDC_1P_RX_SEL				64
#define CLK_TOP_DSP_SEL					65
#define CLK_TOP_EMI_INF_546_SEL				66
#define CLK_TOP_MFG_REF_SEL				67
#define CLK_TOP_MFGSC_REF_SEL				68
#define CLK_TOP_MFG_INT0_SEL				69
#define CLK_TOP_MFG1_INT1_SEL				70
#define CLK_TOP_APLL_SI0_MCK_SEL			71
#define CLK_TOP_APLL_SI1_MCK_SEL			72
#define CLK_TOP_APLL_SI2_MCK_SEL			73
#define CLK_TOP_APLL_SI3_MCK_SEL			74
#define CLK_TOP_APLL_SI4_MCK_SEL			75
#define CLK_TOP_APLL_SI6_MCK_SEL			76
#define CLK_TOP_APLL_SO0_MCK_SEL			77
#define CLK_TOP_APLL_SO1_MCK_SEL			78
#define CLK_TOP_APLL_SO2_MCK_SEL			79
#define CLK_TOP_APLL_SO3_MCK_SEL			80
#define CLK_TOP_APLL_SO4_MCK_SEL			81
#define CLK_TOP_APLL_SO6_MCK_SEL			82
#define CLK_TOP_APLL_FMI2S_MCK_SEL			83
#define CLK_TOP_APLL_TD_MCK_SEL				84
#define CLK_TOP_APLL12_CK_DIV_TD_M			85
#define CLK_TOP_ARMPLL_BL_CK_VRPOC			86
#define CLK_TOP_ARMPLL_LL_CK_VRPOC			87
#define CLK_TOP_CCIPLL					88
#define CLK_TOP_MFGPLL					89
#define CLK_TOP_MFGSCPLL				90
#define CLK_TOP_MAINPLL					91
#define CLK_TOP_MAINPLL_D3				92
#define CLK_TOP_MAINPLL_D4				93
#define CLK_TOP_MAINPLL_D4_D2				94
#define CLK_TOP_MAINPLL_D4_D4				95
#define CLK_TOP_MAINPLL_D4_D8				96
#define CLK_TOP_MAINPLL_D4_D16				97
#define CLK_TOP_MAINPLL_D5				98
#define CLK_TOP_MAINPLL_D5_D2				99
#define CLK_TOP_MAINPLL_D5_D4				100
#define CLK_TOP_MAINPLL_D5_D8				101
#define CLK_TOP_MAINPLL_D6				102
#define CLK_TOP_MAINPLL_D6_D2				103
#define CLK_TOP_MAINPLL_D6_D4				104
#define CLK_TOP_MAINPLL_D6_D8				105
#define CLK_TOP_MAINPLL_D7				106
#define CLK_TOP_MAINPLL_D7_D2				107
#define CLK_TOP_MAINPLL_D7_D4				108
#define CLK_TOP_MAINPLL_D7_D8				109
#define CLK_TOP_MAINPLL_D9				110
#define CLK_TOP_UNIVPLL					111
#define CLK_TOP_UNIVPLL_D2				112
#define CLK_TOP_UNIVPLL_D3				113
#define CLK_TOP_UNIVPLL_D4				114
#define CLK_TOP_UNIVPLL_D4_D2				115
#define CLK_TOP_UNIVPLL_D4_D4				116
#define CLK_TOP_UNIVPLL_D4_D8				117
#define CLK_TOP_UNIVPLL_D5				118
#define CLK_TOP_UNIVPLL_D5_D2				119
#define CLK_TOP_UNIVPLL_D5_D4				120
#define CLK_TOP_UNIVPLL_D5_D8				121
#define CLK_TOP_UNIVPLL_D5_D16				122
#define CLK_TOP_UNIVPLL_D6				123
#define CLK_TOP_UNIVPLL_D6_D2				124
#define CLK_TOP_UNIVPLL_D6_D4				125
#define CLK_TOP_UNIVPLL_D6_D8				126
#define CLK_TOP_UNIVPLL_D6_D16				127
#define CLK_TOP_UNIVPLL_D7				128
#define CLK_TOP_UNIVPLL_D7_D2				129
#define CLK_TOP_UNIVPLL_192M				130
#define CLK_TOP_UVPLL192M_D2				131
#define CLK_TOP_UVPLL192M_D4				132
#define CLK_TOP_UVPLL192M_D8				133
#define CLK_TOP_UVPLL192M_D10				134
#define CLK_TOP_UVPLL192M_D16				135
#define CLK_TOP_UVPLL192M_D32				136
#define CLK_TOP_USB20_192M				137
#define CLK_TOP_USB20_PLL_D2				138
#define CLK_TOP_USB20_PLL_D4				139
#define CLK_TOP_APLL1					140
#define CLK_TOP_APLL1_D2				141
#define CLK_TOP_APLL1_D4				142
#define CLK_TOP_APLL1_D8				143
#define CLK_TOP_APLL2					144
#define CLK_TOP_APLL2_D2				145
#define CLK_TOP_APLL2_D4				146
#define CLK_TOP_APLL2_D8				147
#define CLK_TOP_CLK26M_BYP				148
#define CLK_TOP_MMPLL					149
#define CLK_TOP_MMPLL_D3				150
#define CLK_TOP_MMPLL_D4				151
#define CLK_TOP_MMPLL_D4_D2				152
#define CLK_TOP_MMPLL_D4_D4				153
#define CLK_TOP_MMPLL_D5				154
#define CLK_TOP_MMPLL_D5_D2				155
#define CLK_TOP_MMPLL_D5_D4				156
#define CLK_TOP_MMPLL_D6				157
#define CLK_TOP_MMPLL_D6_D2				158
#define CLK_TOP_MMPLL_D7				159
#define CLK_TOP_MMPLL_D9				160
#define CLK_TOP_UFSPLL					161
#define CLK_TOP_UFSPLL_D2				162
#define CLK_TOP_UFSPLL_D4				163
#define CLK_TOP_UFSPLL_D8				164
#define CLK_TOP_UFSPLL_D16				165
#define CLK_TOP_MSDCPLL					166
#define CLK_TOP_MSDCPLL_D2				167
#define CLK_TOP_MSDCPLL_D4				168
#define CLK_TOP_MSDCPLL_D8				169
#define CLK_TOP_MSDCPLL_D16				170
#define CLK_TOP_ARMPLL_26M				171
#define CLK_TOP_CLKRTC					172
#define CLK_TOP_TCK_26M_MX8				173
#define CLK_TOP_TCK_26M_MX9				174
#define CLK_TOP_TCK_26M_MX10				175
#define CLK_TOP_TCK_26M_MX11				176
#define CLK_TOP_TCK_26M_MX12				177
#define CLK_TOP_CSW_FAXI				178
#define CLK_TOP_F26M_CK_D52				179
#define CLK_TOP_F26M_CK_D2				180
#define CLK_TOP_OSC					181
#define CLK_TOP_OSC_D2					182
#define CLK_TOP_OSC_D3					183
#define CLK_TOP_OSC_D4					184
#define CLK_TOP_OSC_D7					185
#define CLK_TOP_OSC_D8					186
#define CLK_TOP_OSC_D16					187
#define CLK_TOP_OSC_D10					188
#define CLK_TOP_OSC_D20					189
#define CLK_TOP_OSC_CK_2				190
#define CLK_TOP_OSC2_D2					191
#define CLK_TOP_OSC2_D3					192
#define CLK_TOP_OSC2_D5					193
#define CLK_TOP_F26M					194
#define CLK_TOP_RTC					195
#define CLK_TOP_AXI					196
#define CLK_TOP_AXI_P					197
#define CLK_TOP_AXI_UFS					198
#define CLK_TOP_BUS					199
#define CLK_TOP_DISP0					200
#define CLK_TOP_MMINFRA					201
#define CLK_TOP_MMUP					202
#define CLK_TOP_CAMTG					203
#define CLK_TOP_CAMTG2					204
#define CLK_TOP_CAMTG3					205
#define CLK_TOP_CAMTG4					206
#define CLK_TOP_CAMTG5					207
#define CLK_TOP_CAMTG6					208
#define CLK_TOP_UART					209
#define CLK_TOP_SPI0					210
#define CLK_TOP_SPI1					211
#define CLK_TOP_SPI2					212
#define CLK_TOP_SPI3					213
#define CLK_TOP_SPI4					214
#define CLK_TOP_SPI5					215
#define CLK_TOP_SPI6					216
#define CLK_TOP_SPI7					217
#define CLK_TOP_MSDC_0P					218
#define CLK_TOP_MSDC50_0_HCLK				219
#define CLK_TOP_MSDC50_0				220
#define CLK_TOP_AES_MSDCFDE				221
#define CLK_TOP_MSDC_1P					222
#define CLK_TOP_MSDC30_1				223
#define CLK_TOP_MSDC30_1_HCLK				224
#define CLK_TOP_AUD_INTBUS				225
#define CLK_TOP_ATB					226
#define CLK_TOP_DISP_PWM				227
#define CLK_TOP_USB_TOP					228
#define CLK_TOP_USB_XHCI				229
#define CLK_TOP_I2C					230
#define CLK_TOP_SENINF					231
#define CLK_TOP_SENINF1					232
#define CLK_TOP_SENINF2					233
#define CLK_TOP_SENINF3					234
#define CLK_TOP_AUD_ENGEN1				235
#define CLK_TOP_AUD_ENGEN2				236
#define CLK_TOP_AES_UFSFDE				237
#define CLK_TOP_UFS					238
#define CLK_TOP_UFS_MBIST				239
#define CLK_TOP_AUD_1					240
#define CLK_TOP_AUD_2					241
#define CLK_TOP_DPMAIF_MAIN				242
#define CLK_TOP_VENC					243
#define CLK_TOP_VDEC					244
#define CLK_TOP_PWM					245
#define CLK_TOP_AUDIO_H					246
#define CLK_TOP_MCUPM					247
#define CLK_TOP_MEM_SUB					248
#define CLK_TOP_MEM_SUB_P				249
#define CLK_TOP_MEM_SUB_UFS				250
#define CLK_TOP_EMI_N					251
#define CLK_TOP_DSI_OCC					252
#define CLK_TOP_AP2CONN_HOST				253
#define CLK_TOP_IMG1					254
#define CLK_TOP_IPE					255
#define CLK_TOP_CAM					256
#define CLK_TOP_CCUSYS					257
#define CLK_TOP_CAMTM					258
#define CLK_TOP_CCU_AHB					259
#define CLK_TOP_CCUTM					260
#define CLK_TOP_MSDC_1P_RX				261
#define CLK_TOP_DSP					262
#define CLK_TOP_EMI_INF_546				263
#define CLK_TOP_SR_PKA					264
#define CLK_TOP_SR_DMA					265
#define CLK_TOP_SR_KDF					266
#define CLK_TOP_SR_RNG					267
#define CLK_TOP_DXCC					268
#define CLK_TOP_MFG_REF					269
#define CLK_TOP_MFG_INT0				270
#define CLK_TOP_MFG1_INT1				271
#define CLK_TOP_MFGSC_REF				272
#define CLK_TOP_ULPOSC					273
#define CLK_TOP_ULPOSC_CORE				274
#define CLK_TOP_APLL12_DIV_SI1				275
#define CLK_TOP_APLL12_DIV_SI2				276
#define CLK_TOP_APLL12_DIV_SI4				277
#define CLK_TOP_APLL12_DIV_SO1				278
#define CLK_TOP_APLL12_DIV_SO2				279
#define CLK_TOP_APLL12_DIV_SO4				280
#define CLK_TOP_APLL12_DIV_FMI2S			281
#define CLK_TOP_NR_CLK					282

/* INFRA_AO_REG */
#define CLK_IFRAO_CQ_DMA_FPC				0
#define CLK_IFRAO_CCIF1_AP				1
#define CLK_IFRAO_CCIF1_MD				2
#define CLK_IFRAO_CCIF_AP				3
#define CLK_IFRAO_CCIF_MD				4
#define CLK_IFRAO_CLDMA_BCLK				5
#define CLK_IFRAO_CQ_DMA				6
#define CLK_IFRAO_CCIF5_MD				7
#define CLK_IFRAO_CCIF2_AP				8
#define CLK_IFRAO_CCIF2_MD				9
#define CLK_IFRAO_DPMAIF_MAIN				10
#define CLK_IFRAO_CCIF4_MD				11
#define CLK_IFRAO_RG_MMW_DPMAIF26M		    12
#define CLK_IFRAO_NR_CLK				13

/* APMIXEDSYS */
#define CLK_APMIXED_ARMPLL_LL				0
#define CLK_APMIXED_ARMPLL_BL				1
#define CLK_APMIXED_CCIPLL				2
#define CLK_APMIXED_MAINPLL				3
#define CLK_APMIXED_UNIVPLL				4
#define CLK_APMIXED_MSDCPLL				5
#define CLK_APMIXED_MMPLL				6
#define CLK_APMIXED_UFSPLL				7
#define CLK_APMIXED_APLL1				8
#define CLK_APMIXED_APLL2				9
#define CLK_APMIXED_NR_CLK				10


/* PERICFG_AO */
#define CLK_PERAOP_UART0				0
#define CLK_PERAOP_UART1				1
#define CLK_PERAOP_UART2				2
#define CLK_PERAOP_PWM_H				3
#define CLK_PERAOP_PWM_B				4
#define CLK_PERAOP_PWM_FB1				5
#define CLK_PERAOP_PWM_FB2				6
#define CLK_PERAOP_PWM_FB3				7
#define CLK_PERAOP_PWM_FB4				8
#define CLK_PERAOP_SPI0_B				9
#define CLK_PERAOP_SPI1_B				10
#define CLK_PERAOP_SPI2_B				11
#define CLK_PERAOP_SPI3_B				12
#define CLK_PERAOP_SPI4_B				13
#define CLK_PERAOP_SPI5_B				14
#define CLK_PERAOP_SPI6_B				15
#define CLK_PERAOP_SPI7_B				16
#define CLK_PERAOP_DMA_B				17
#define CLK_PERAOP_SSUSB0_FRMCNT			18
#define CLK_PERAOP_MSDC0				19
#define CLK_PERAOP_MSDC0_H				20
#define CLK_PERAOP_MSDC0_FAES				21
#define CLK_PERAOP_MSDC0_MST_F				22
#define CLK_PERAOP_MSDC0_SLV_H				23
#define CLK_PERAOP_MSDC1				24
#define CLK_PERAOP_MSDC1_H				25
#define CLK_PERAOP_MSDC1_MST_F				26
#define CLK_PERAOP_MSDC1_SLV_H				27
#define CLK_PERAOP_AUDIO0				28
#define CLK_PERAOP_AUDIO1				29
#define CLK_PERAOP_AUDIO2				30
#define CLK_PERAO_NR_CLK				31

/* AFE */
#define CLK_AFE_DL0_DAC_TML				0
#define CLK_AFE_DL0_DAC_HIRES				1
#define CLK_AFE_DL0_DAC					2
#define CLK_AFE_DL0_PREDIS				3
#define CLK_AFE_DL0_NLE					4
#define CLK_AFE_PCM1					5
#define CLK_AFE_PCM0					6
#define CLK_AFE_CM1					7
#define CLK_AFE_CM0					8
#define CLK_AFE_STF					9
#define CLK_AFE_HW_GAIN23				10
#define CLK_AFE_HW_GAIN01				11
#define CLK_AFE_FM_I2S					12
#define CLK_AFE_MTKAIFV4				13
#define CLK_AFE_UL1_ADC_HIRES_TML			14
#define CLK_AFE_UL1_ADC_HIRES				15
#define CLK_AFE_UL1_TML					16
#define CLK_AFE_UL1_ADC					17
#define CLK_AFE_UL0_ADC_HIRES_TML			18
#define CLK_AFE_UL0_ADC_HIRES				19
#define CLK_AFE_UL0_TML					20
#define CLK_AFE_UL0_ADC					21
#define CLK_AFE_ETDM_IN4				22
#define CLK_AFE_ETDM_IN2				23
#define CLK_AFE_ETDM_IN1				24
#define CLK_AFE_ETDM_OUT4				25
#define CLK_AFE_ETDM_OUT2				26
#define CLK_AFE_ETDM_OUT1				27
#define CLK_AFE_GENERAL2_ASRC				28
#define CLK_AFE_GENERAL1_ASRC				29
#define CLK_AFE_GENERAL0_ASRC				30
#define CLK_AFE_CONNSYS_I2S_ASRC			31
#define CLK_AFE_AUDIO_HOPPING				32
#define CLK_AFE_AUDIO_F26M				33
#define CLK_AFE_APLL1					34
#define CLK_AFE_APLL2					35
#define CLK_AFE_H208M					36
#define CLK_AFE_APLL_TUNER2				37
#define CLK_AFE_APLL_TUNER1				38
#define CLK_AFE_NR_CLK					39

/* IMP_IIC_WRAP_CEN_S */
#define CLK_IM_C_S_I3C5_W1S				0
#define CLK_IM_C_S_SEC_EN_W1S				1
#define CLK_IM_C_S_NR_CLK				2

/* UFSCFG_AO */
#define CLK_UFSAO_UNIPRO_TX_SYM				0
#define CLK_UFSAO_UNIPRO_RX_SYM0			1
#define CLK_UFSAO_UNIPRO_RX_SYM1			2
#define CLK_UFSAO_UNIPRO_SYS				3
#define CLK_UFSAO_UNIPRO_SAP_CFG			4
#define CLK_UFSAO_PHY_TOP_AHB_S_BUS			5
#define CLK_UFSAO_NR_CLK				6

/* UFSCFG_PDN */
#define CLK_UFSPDN_UFSHCI				0
#define CLK_UFSPDN_UFSHCI_AES				1
#define CLK_UFSPDN_UFSHCI_AHB				2
#define CLK_UFSPDN_UFSHCI_AXI				3
#define CLK_UFSPDN_NR_CLK				4

/* IMP_IIC_WRAP_E_S */
#define CLK_IMP_E_S_I3C0_W1S				0
#define CLK_IMP_E_S_I3C1_W1S				1
#define CLK_IMP_E_S_I3C2_W1S				2
#define CLK_IMP_E_S_I3C4_W1S				3
#define CLK_IMP_E_S_I3C9_W1S				4
#define CLK_IMP_E_S_SEC_EN_W1S				5
#define CLK_IMP_E_S_NR_CLK				6

/* IMP_IIC_WRAP_ES_S */
#define CLK_IMP_ES_S_I3C10_W1S				0
#define CLK_IMP_ES_S_I3C11_W1S				1
#define CLK_IMP_ES_S_I3C12_W1S				2
#define CLK_IMP_ES_S_SEC_EN_W1S				3
#define CLK_IMP_ES_S_NR_CLK				4

/* IMP_IIC_WRAP_W_S */
#define CLK_IMP_W_S_I3C3_W1S				0
#define CLK_IMP_W_S_I3C6_W1S				1
#define CLK_IMP_W_S_I3C7_W1S				2
#define CLK_IMP_W_S_I3C8_W1S				3
#define CLK_IMP_W_S_SEC_EN_W1S				4
#define CLK_IMP_W_S_NR_CLK				5

/* MFGPLL_PLL_CTRL */
#define CLK_MFG_AO_MFGPLL				0
#define CLK_MFG_AO_NR_CLK				1

/* MFGSCPLL_PLL_CTRL */
#define CLK_MFGSC_AO_MFGSCPLL				0
#define CLK_MFGSC_AO_NR_CLK				1

/* DISPSYS_CONFIG */
#define CLK_MM_DISP_OVL0_2L				0
#define CLK_MM_DISP_OVL1_2L				1
#define CLK_MM_DISP_OVL2_2L				2
#define CLK_MM_DISP_OVL3_2L				3
#define CLK_MM_DISP_UFBC_WDMA0				4
#define CLK_MM_DISP_RSZ1				5
#define CLK_MM_DISP_RSZ0				6
#define CLK_MM_DISP_TDSHP0				7
#define CLK_MM_DISP_C3D0				8
#define CLK_MM_DISP_COLOR0				9
#define CLK_MM_DISP_CCORR0				10
#define CLK_MM_DISP_CCORR1				11
#define CLK_MM_DISP_AAL0				12
#define CLK_MM_DISP_GAMMA0				13
#define CLK_MM_DISP_POSTMASK0				14
#define CLK_MM_DISP_DITHER0				15
#define CLK_MM_DISP_TDSHP1				16
#define CLK_MM_DISP_C3D1				17
#define CLK_MM_DISP_CCORR2				18
#define CLK_MM_DISP_CCORR3				19
#define CLK_MM_DISP_GAMMA1				20
#define CLK_MM_DISP_DITHER1				21
#define CLK_MM_DISP_SPLITTER0				22
#define CLK_MM_DISP_DSC_WRAP0				23
#define CLK_MM_DISP_DSI0				24
#define CLK_MM_DISP_DSI1				25
#define CLK_MM_DISP_WDMA1				26
#define CLK_MM_DISP_APB_BUS				27
#define CLK_MM_DISP_FAKE_ENG0				28
#define CLK_MM_DISP_FAKE_ENG1				29
#define CLK_MM_DISP_MUTEX0				30
#define CLK_MM_SMI_COMMON				31
#define CLK_MM_DSI0					32
#define CLK_MM_DSI1					33
#define CLK_MM_26M					34
#define CLK_MM_NR_CLK					35

/* IMGSYS_MAIN */
#define CLK_IMG_FDVT					0
#define CLK_IMG_ME					1
#define CLK_IMG_MMG					2
#define CLK_IMG_LARB12					3
#define CLK_IMG_LARB9					4
#define CLK_IMG_TRAW0					5
#define CLK_IMG_TRAW1					6
#define CLK_IMG_DIP0					7
#define CLK_IMG_WPE0					8
#define CLK_IMG_IPE					9
#define CLK_IMG_WPE1					10
#define CLK_IMG_WPE2					11
#define CLK_IMG_SUB_COMMON0				12
#define CLK_IMG_SUB_COMMON1				13
#define CLK_IMG_SUB_COMMON3				14
#define CLK_IMG_SUB_COMMON4				15
#define CLK_IMG_GALS_RX_DIP0				16
#define CLK_IMG_GALS_RX_DIP1				17
#define CLK_IMG_GALS_RX_TRAW0				18
#define CLK_IMG_GALS_RX_WPE0				19
#define CLK_IMG_GALS_RX_WPE1				20
#define CLK_IMG_GALS_RX_IPE0				21
#define CLK_IMG_GALS_TX_IPE0				22
#define CLK_IMG_GALS					23
#define CLK_IMG_NR_CLK					24

/* DIP_TOP_DIP1 */
#define CLK_DIP_TOP_DIP1_DIP_TOP			0
#define CLK_DIP_TOP_DIP1_DIP_TOP_GALS0			1
#define CLK_DIP_TOP_DIP1_DIP_TOP_GALS1			2
#define CLK_DIP_TOP_DIP1_DIP_TOP_GALS2			3
#define CLK_DIP_TOP_DIP1_DIP_TOP_GALS3			4
#define CLK_DIP_TOP_DIP1_LARB10				5
#define CLK_DIP_TOP_DIP1_LARB15				6
#define CLK_DIP_TOP_DIP1_LARB38				7
#define CLK_DIP_TOP_DIP1_LARB39				8
#define CLK_DIP_TOP_DIP1_NR_CLK				9

/* DIP_NR1_DIP1 */
#define CLK_DIP_NR1_DIP1_LARB				0
#define CLK_DIP_NR1_DIP1_DIP_NR1			1
#define CLK_DIP_NR1_DIP1_NR_CLK				2

/* DIP_NR2_DIP1 */
#define CLK_DIP_NR2_DIP1_LARB15				0
#define CLK_DIP_NR2_DIP1_DIP_NR				1
#define CLK_DIP_NR2_DIP1_NR_CLK				2

/* WPE1_DIP1 */
#define CLK_WPE1_DIP1_LARB11				0
#define CLK_WPE1_DIP1_WPE				1
#define CLK_WPE1_DIP1_GALS0				2
#define CLK_WPE1_DIP1_NR_CLK				3

/* WPE2_DIP1 */
#define CLK_WPE2_DIP1_LARB11				0
#define CLK_WPE2_DIP1_WPE				1
#define CLK_WPE2_DIP1_GALS0				2
#define CLK_WPE2_DIP1_NR_CLK				3

/* TRAW_DIP1 */
#define CLK_TRAW_DIP1_LARB28				0
#define CLK_TRAW_DIP1_LARB40				1
#define CLK_TRAW_DIP1_TRAW				2
#define CLK_TRAW_DIP1_GALS				3
#define CLK_TRAW_DIP1_NR_CLK				4

/* IMG_VCORE_D1A */
#define CLK_IMG_VCORE_GALS_DISP				0
#define CLK_IMG_VCORE_MAIN				1
#define CLK_IMG_VCORE_SUB0				2
#define CLK_IMG_VCORE_SUB1				3
#define CLK_IMG_V_NR_CLK				4

/* VDEC_GCON_BASE */
#define CLK_VDE2_LARB_CKEN				0
#define CLK_VDE2_VDEC_CKEN				1
#define CLK_VDE2_VDEC_ACTIVE				2
#define CLK_VDE2_NR_CLK					3

/* VENC_GCON */
#define CLK_VEN1_CKE0_LARB				0
#define CLK_VEN1_CKE1_VENC				1
#define CLK_VEN1_CKE2_JPGENC				2
#define CLK_VEN1_CKE5_GALS				3
#define CLK_VEN1_NR_CLK					4

/* VLP_CKSYS */
#define CLK_VLP_SCP_SEL					0
#define CLK_VLP_PWRAP_ULPOSC_SEL			1
#define CLK_VLP_SPMI_P_MST_SEL				2
#define CLK_VLP_SPMI_M_MST_SEL				3
#define CLK_VLP_DVFSRC_SEL				4
#define CLK_VLP_PWM_VLP_SEL				5
#define CLK_VLP_AXI_VLP_SEL				6
#define CLK_VLP_DBGAO_26M_SEL				7
#define CLK_VLP_SYSTIMER_26M_SEL			8
#define CLK_VLP_SSPM_SEL				9
#define CLK_VLP_SSPM_F26M_SEL				10
#define CLK_VLP_SRCK_SEL				11
#define CLK_VLP_SCP_SPI_SEL				12
#define CLK_VLP_SCP_IIC_SEL				13
#define CLK_VLP_SCP_SPI_HS_SEL				14
#define CLK_VLP_SCP_IIC_HS_SEL				15
#define CLK_VLP_SSPM_ULPOSC_SEL				16
#define CLK_VLP_APXGPT_26M_SEL				17
#define CLK_VLP_SCP					18
#define CLK_VLP_PWRAP_ULPOSC				19
#define CLK_VLP_SPMI_P_MST				20
#define CLK_VLP_SPMI_M_MST				21
#define CLK_VLP_DVFSRC					22
#define CLK_VLP_PWM_VLP					23
#define CLK_VLP_AXI_VLP					24
#define CLK_VLP_DBGAO_26M				25
#define CLK_VLP_SYSTIMER_26M				26
#define CLK_VLP_SSPM					27
#define CLK_VLP_SSPM_F26M				28
#define CLK_VLP_SRCK					29
#define CLK_VLP_SCP_SPI					30
#define CLK_VLP_SCP_IIC					31
#define CLK_VLP_SCP_SPI_HS				32
#define CLK_VLP_SCP_IIC_HS				33
#define CLK_VLP_SSPM_ULPOSC				34
#define CLK_VLP_TIA_ULPOSC				35
#define CLK_VLP_APXGPT_26M				36
#define CLK_VLP_SPM					37
#define CLK_VLP_NR_CLK					38

/* SCP */
#define CLK_SCP_SET_SPI0				0
#define CLK_SCP_SET_SPI1				1
#define CLK_SCP_SET_SPI2				2
#define CLK_SCP_SET_SPI3				3
#define CLK_SCP_NR_CLK					4

/* CAMSYS_MAIN */
#define CLK_CAM_MAIN_LARB13				0
#define CLK_CAM_MAIN_LARB14				1
#define CLK_CAM_MAIN_LARB29				2
#define CLK_CAM_MAIN_CAM				3
#define CLK_CAM_MAIN_CAM_SUBA				4
#define CLK_CAM_MAIN_CAM_SUBB				5
#define CLK_CAM_MAIN_CAM_MRAW				6
#define CLK_CAM_MAIN_CAMTG				7
#define CLK_CAM_MAIN_SENINF				8
#define CLK_CAM_MAIN_CAMSV_TOP				9
#define CLK_CAM_MAIN_CAM2MM0_GALS			10
#define CLK_CAM_MAIN_CAM2MM1_GALS			11
#define CLK_CAM_MAIN_CCUSYS				12
#define CLK_CAM_MAIN_CAM_ASG				13
#define CLK_CAM_MAIN_CAMSV_A_CON_1			14
#define CLK_CAM_MAIN_CAMSV_B_CON_1			15
#define CLK_CAM_MAIN_CAMSV_C_CON_1			16
#define CLK_CAM_MAIN_CAMSV_D_CON_1			17
#define CLK_CAM_MAIN_CAMSV_E_CON_1			18
#define CLK_CAM_MAIN_CAMSV_CON_1			19
#define CLK_CAM_M_NR_CLK				20

/* CAMSYS_RAWA */
#define CLK_CAM_RA_LARBX				0
#define CLK_CAM_RA_CAM					1
#define CLK_CAM_RA_CAMTG				2
#define CLK_CAM_RA_RAW2MM_GALS				3
#define CLK_CAM_RA_YUV2RAW2MM_GALS			4
#define CLK_CAM_RA_NR_CLK				5

/* CAMSYS_YUVA */
#define CLK_CAM_YA_LARBX				0
#define CLK_CAM_YA_CAM					1
#define CLK_CAM_YA_CAMTG				2
#define CLK_CAM_YA_NR_CLK				3

/* CAMSYS_RAWB */
#define CLK_CAM_RB_LARBX				0
#define CLK_CAM_RB_CAM					1
#define CLK_CAM_RB_CAMTG				2
#define CLK_CAM_RB_RAW2MM_GALS				3
#define CLK_CAM_RB_YUV2RAW2MM_GALS			4
#define CLK_CAM_RB_NR_CLK				5

/* CAMSYS_YUVB */
#define CLK_CAM_YB_LARBX				0
#define CLK_CAM_YB_CAM					1
#define CLK_CAM_YB_CAMTG				2
#define CLK_CAM_YB_NR_CLK				3

/* CAMSYS_MRAW */
#define CLK_CAM_MR_LARBX				0
#define CLK_CAM_MR_GALS					1
#define CLK_CAM_MR_CAMTG				2
#define CLK_CAM_MR_MRAW0				3
#define CLK_CAM_MR_MRAW1				4
#define CLK_CAM_MR_MRAW2				5
#define CLK_CAM_MR_MRAW3				6
#define CLK_CAM_MR_PDA0					7
#define CLK_CAM_MR_PDA1					8
#define CLK_CAM_MR_NR_CLK				9

/* CCU_MAIN */
#define CLK_CCU_LARB30_CON				0
#define CLK_CCU_AHB_CON					1
#define CLK_CCUSYS_CCU0_CON				2
#define CLK_CCU2MM0_GALS_CON				3
#define CLK_CCU_NR_CLK					4

/* CAM_VCORE */
#define CLK_CAM_VCORE_C2MM0_DCM_DIS			0
#define CLK_CAM_VCORE_MM0_DCM_DIS			1
#define CLK_CAM_VCORE_NR_CLK				2

/* MMINFRA_CONFIG */
#define CLK_MMINFRA_GCE_D				0
#define CLK_MMINFRA_GCE_M				1
#define CLK_MMINFRA_GCE_26M				2
#define CLK_MMINFRA_CONFIG_NR_CLK			3

/* MDPSYS_CONFIG */
#define CLK_MDP_MUTEX0					0
#define CLK_MDP_APB_BUS					1
#define CLK_MDP_SMI0					2
#define CLK_MDP_RDMA0					3
#define CLK_MDP_HDR0					4
#define CLK_MDP_AAL0					5
#define CLK_MDP_RSZ0					6
#define CLK_MDP_TDSHP0					7
#define CLK_MDP_WROT0					8
#define CLK_MDP_RDMA1					9
#define CLK_MDP_RSZ1					10
#define CLK_MDP_WROT1					11
#define CLK_MDP_NR_CLK					12

#endif /* _DT_BINDINGS_CLK_MT6878_H */
