# SPDX-License-Identifier: GPL-2.0
# CPUfreq core

##################################################################################
# ARM SoC drivers
obj-$(CONFIG_DEVICE_MODULES_ARM_MEDIATEK_CPUFREQ_HW)	+= mediatek-cpufreq-hw.o
