# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC)	+= mtk-vcodec/

obj-$(CONFIG_VIDEO_MEDIATEK_VCU)	+= mtk-vcu/

obj-$(CONFIG_VIDEO_MEDIATEK_JPEG)	+= mtk-jpeg/

obj-y					+= mtk-isp/

obj-$(CONFIG_MTK_CAMERA_FD_ISP7S)	+= mtk-aie/
